frontend:
  - frontend/**/*

backend:
  - backend/**/*

database:
  - backend/prisma/schema.prisma
  - backend/prisma/migrations/**/*

devops:
  - frontend/Dockerfile
  - backend/Dockerfile
  - docker-compose.yml
  - docker-compose.override.yml
  - docker-compose.prod.yml

test:
  - frontend/*.test.tsx
  - backendend/*.test.tsx

docs:
  - README.md
  - frontend/README.md
  - backend/README.md
  - docs/**/*.md
