frontend:
  - frontend/**/*

backend:
  - backend/**/*

devops:
  - frontend/Dockerfile
  - backend/Dockerfile
  - docker-compose.yml
  - docker-compose.override.yml
  - docker-compose.prod.yml

test:
  - **/*.test.tsx

docs:
  - README.md
  - **/README.md
