frontend:
  - ./frontend/**/*

backend:
  - ./backend/**/*

devops:
  - ./**/Dockerfile
  - ./docker-compose.yml
  - ./docker-compose.override.yml
  - ./docker-compose.prod.yml

test:
  - ./**/*.test.tsx

docs:
  - ./README.md
  - ./**/README.md
