version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build:nexus
          name: Build Nexus
      - run:
          command: npm run build:next
          name: Build Next

workflows:
  main:
    jobs:
      - build
