version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
        - run:
            command: npm ci
            name: Installing NPM packages
        - save_cache:
            key: node-deps-{{ checksum "package-lock.json" }}
            paths:
                - ~/.npm
                - ./.next/cache
      - run:
          command: npm run build:nexus
          name: Build Nexus
      - run:
          command: npm run build:next
          name: Build Next

workflows:
  main:
    jobs:
      - build
