version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
      - run:
          command: npm ci
          name: Installing NPM packages
      - run:
          command: npm run build:nexus
          name: Build Nexus
      - run:
          command: npm run build:next
          name: Build Next
      - save_cache:
          key: node-deps-{{ checksum "package-lock.json" }}
          paths:
              - ~/.npm
              - ~/.cache
              - ./.next/cache

workflows:
  main:
    jobs:
      - build
