service: j-mail

custom:
  dotenv:
    include:
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_USER
      - MAIL_PASSWORD
      - MAIL_SECURE
      - AWS_ACCOUNT_ID

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless-admin
  region: us-west-1

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
      Resource: 'arn:aws:sqs:${self:provider.region}:*:JMailQueue'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  processJMailQueue:
    handler: handler.processJMailQueue
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - JMailQueue
              - Arn
          batchSize: 10

resources:
  Resources:
    JMailQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'JMailQueue'
        RedrivePolicy:
          deadLetterTargetArn:
            'Fn::GetAtt':
              - JMailDeadLetterQueue
              - Arn
          maxReceiveCount: 3
    JMailDeadLetterQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'JMailDeadLetterQueue'
        MessageRetentionPeriod: 1209600

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
