service: j-mail

custom:
  settings:
    ACCOUNT_ID: ${process.env.AWS_ACCOUNT_ID}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  environment: ${self:custom.settings}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
      Resource: 'arn:aws:sqs:${self:provider.region}:*:JMailQueue'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
        method: get
        path: hello
  sqsHello:
    handler: handler.sqsHello
    events:
      - sqs:
        arn:
          Fn::GetAtt:
            - JMailQueue
            - Arn
        batchSize: 1

resources:
  Resources:
    JMailQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'JMailQueue'
