service: j-mail

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  environment:
    MAIL_HOST: ${file(./.env.${opt:stage, ''})}
    MAIL_PORT: ${file(./.env.${opt:stage, ''})}
    MAIL_USER: ${file(./.env.${opt:stage, ''})}
    MAIL_PASSWORD: ${file(./.env.${opt:stage, ''})}
    MAIL_SECURE: ${file(./.env.${opt:stage, ''})}
    JAWS_ACCOUNT_ID: ${file(./.env.${opt:stage, ''})}
  runtime: nodejs12.x
  profile: serverless-admin
  region: us-east-2

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
      Resource: 'arn:aws:sqs:${self:provider.region}:*:JMailQueue-${opt:stage}'

functions:
  processJMailQueue:
    handler: handler.processJMailQueue
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - JMailQueue
              - Arn
          batchSize: 10

resources:
  Resources:
    JMailQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'JMailQueue-${opt:stage}'
        RedrivePolicy:
          deadLetterTargetArn:
            'Fn::GetAtt':
              - JMailDeadLetterQueue
              - Arn
          maxReceiveCount: 3
    JMailDeadLetterQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'JMailDeadLetterQueue-${opt:stage}'
        MessageRetentionPeriod: 1209600

plugins:
  - serverless-plugin-typescript
